name: HelloBoar Docker Image CI

on:
  workflow_dispatch:
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - uses:  docker/login-action@v1
     - name: Docker hub login image
       with:
          username:${{secrets.DOCKER_USER}}
          password:${{secrets.DOCKER_PASSWORD}}
       
                 
     - name: Build and push
       id: docker_build
       uses: docker/build-push-action@v2
       with:
          push: true
          tags: davanzini/helloboar:latest
